### PR TITLE
Extract serializers from InceptumMessaging to separate assemblies

### PR DESCRIPTION
**Pull request by tripolitov**
Extract serializers from InceptumMessaging to separate assemblies this will remove the dependency on protobuf-net when using MessagingEngine.

But will force consumers of MessagingEngine register required serializer factories explicitly within messaging engine by calling RegisterSerializerFactory or by registering a service which implements ISerializerFactory within Castle IoC.

### CODE REVIEW

**Comment by usverger** [comment]
не смотрел, но закрывайте.

**Comment by tvilkov** [comment]
Dependency graph seems a bit strange to me. 
You install `lnceptum.Messaging.Serialization.Json` and get **implicit** dependency on `lnceptum.Messaging` itself. So if someone want to introduce another serializer he'll have to reference whole `lnceptum.Messaging`.
I'd suggest introducing something like `lnceptum.Messaging.Abstractions` with all the interfaces. Then 
`lnceptum.Messaging.Serialization.*` can reference it instead of heavy `lnceptum.Messaging`.

**Comment by tripolitov** [comment]
The purpose of this change was to extract Serialization implementations from Inceptum.Messaging so consumer won't have a dependency on protobuf-net or newtonsoft json when it is not needed. 

The intent to extract ISerializerFactory and ISerializer interfaces from messaging to separate must be the ability to reuse implementations in different projects which don't use Inceptum.Messaging, it's a good point and can be done somewhere in the future.  But lnceptum.Messaging.Abstractions sonwnds a bit awkward for me, maybe, it is a good idea to introduce some kind of Inceptum.Serialization package to hold all serialization abstractions like ISerializerFactory and ISerializer and base algorithms. So other Inceptum projects like Inceptum.Sprache or others can somehow benefit from this new package.

**Comment by KonstantinNosov** [comment]
If there is no JsonSerializerFactory by default, it makes sense to explicitly tell to user that he has to register one.

**Comment by KonstantinNosov** [comment]
Consider adding Inceptum.Messaging.Serialization.Protobuf utilizing native google protobuf implementation

**Comment by tripolitov** [comment]
> If there is no JsonSerializerFactory by default, it makes sense to explicitly tell to user that he has to register one.

As far as I understand this is only possible when Serializers are constructed in `SerializationManager`  class in method called `ExtractSerializer` and it already has quite understandable error message which states that `{1} serializer for type {0} not found` wheree `{1}` is format ('json', 'protobuf', etc) and `{2}` is name of message type 'typeof(TMessage)`. 

Also it is not mandatory to have an instance of ISerializerFactory be registered within MessageingEngine as consumer can resister specific serializers with `RegisterSerializer` method.

> Consider adding Inceptum.Messaging.Serialization.Protobuf utilizing native google protobuf implementation

This PR is just to extract dependency from Inceptum.Messaging package. Lets go with Google.Protobuf in another PR if it is really needed.

**Comment by KonstantinNosov** [comment]
Agree on both items. Merging

**Pull request merged**
